In [1]:
import pandas as pd
wc = pd.read_csv('ODI_match.csv')
#wc = wc[wc['bat_team']=="United Arab Emirates"]
#wc = wc[wc['bowl_team']=="West Indies"]
dataset = pd.read_csv('odi.csv')
dataset = dataset[dataset['bat_team']=="India"]
dataset = dataset[dataset['bowl_team']=="England"]
dataset = dataset[dataset['date']=="2013-01-11"]
wc

mid       date          venue              bat_team    bowl_team  \
0    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
1    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
2    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
3    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
4    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
5    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
6    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
7    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
8    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
9    836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
10   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
11   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
12   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
13   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
14   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
15   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
16   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
17   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
18   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
19   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
20   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
21   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
22   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
23   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
24   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
25   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
26   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
27   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
28   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
29   836  3/15/2015    McLean Park  United Arab Emirates  West Indies   
..   ...        ...            ...                   ...          ...   
576  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
577  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
578  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
579  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
580  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
581  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
582  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
583  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
584  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
585  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
586  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
587  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
588  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
589  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
590  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
591  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
592  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
593  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
594  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
595  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
596  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
597  837  3/15/2015  Adelaide Oval               Ireland     Pakistan   
598  837  3/15/2015  Adelaide Oval               Ireland     Pa

In [2]:
X = wc.iloc[:,[7,8,9,12,13]].values #Input features
X

array([[1.00e+00, 0.00e+00, 1.00e-01, 1.00e+00, 0.00e+00],
       [2.00e+00, 0.00e+00, 2.00e-01, 1.00e+00, 1.00e+00],
       [2.00e+00, 0.00e+00, 3.00e-01, 1.00e+00, 1.00e+00],
       ...,
       [2.37e+02, 9.00e+00, 4.94e+01, 1.10e+01, 1.00e+00],
       [2.37e+02, 9.00e+00, 4.95e+01, 1.10e+01, 1.00e+00],
       [2.37e+02, 1.00e+01, 4.96e+01, 1.10e+01, 1.00e+00]])

In [3]:
y = wc.iloc[:, 14].values #Label
y

array([175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
       175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 17

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
ODIsc = StandardScaler()
X_train = ODIsc.fit_transform(X_train)
X_test = ODIsc.transform(X_test)

In [6]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
y_pred = lr.predict(X_test)
score = lr.score(X_test,y_test)*100
print("R-squared value:" , score)


R-squared value: 79.41944555151525


In [8]:
def accuracy(y_test,y_pred,frequency):
    r = 0
    l = len(y_pred)
    for i in range(0,l):
        if(abs(y_pred[i]-y_test[i]) <= frequency):
            r= r+1
    return ((r/l)*100)


In [9]:
print("accuracy of the model:" , accuracy(y_test,y_pred,30))


accuracy of the model: 93.4065934065934


In [31]:
import numpy as np
new_prediction = lr.predict(ODIsc.transform((dataset.iloc[:,[7,8,9,12,13]])))
new_prediction

array([217.33682424, 216.97120597, 216.6055877 , 220.95873796,
       220.59311969, 220.22750142, 222.16184219, 222.97591606,
       222.61029779, 222.24467952, 221.87906125, 222.45405101,
       220.62595967, 221.44003353, 221.07441526, 220.70879699,
       220.34317872, 220.91816848, 223.80884567, 224.62291953,
       224.25730126, 227.65411511, 227.28849684, 226.92287857,
       229.81355576, 234.16670602, 238.51985628, 239.33393015,
       238.96831188, 242.36512572, 241.71672651, 245.11354036,
       244.74792209, 244.38230382, 244.01668555, 244.59167531,
       244.64480002, 244.27918176, 244.85417152, 245.66824538,
       247.18384317, 251.05882522, 249.23073388, 248.86511561,
       248.49949734, 248.13387907, 247.7682608 , 248.34325056,
       247.45576725, 247.09014898, 247.90422284, 248.4792126 ,
       249.29328646, 249.86827622, 248.04018488, 247.67456661,
       248.48864047, 248.12302221, 248.69801197, 253.05116223,
       251.22307088, 251.79806064, 251.43244237, 251.06